### ISSUE TITLE
We need to update this bro!

### ISSUE THREAD

**Issue by cyberjock** [justinjereza/Lagari#1]
@justinjereza Hey man!  Long time no chat.  I was gonna email you, but I don't have your email anymore.  Anyway, I think its time to update this.  A few things have changed since 2014 in Minecraft and this doesn't work right anymore.  Wanna make a little money and help me update this?

I have no idea how to contact you except through here.  I Paypal'd you money, but Paypal doesn't let me go back to 2014.  LOL!

I'm not on the FreeNAS forums much anymore, but let me know if you are still active on Github.  Maybe we can get together!

Take care!

**Comment by justinjereza** [comment]
@cyberjock Hello. I didn't notice this issue until now. What has changed with Minecraft? What server are you using now? I'm on libera.chat nowadays so you can just send me a message there if you want.

**Comment by cyberjock** [comment]
What's your IRC username?  I joined libra irc as cyberjock even though I don't use that name anymore. :P

**Comment by cyberjock** [comment]
You still alive?  LOL.
